services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file: .env.production
    volumes:
      - /etc/skill-test/storages:/app/storages
      - /etc/skill-test/temp:/app/temp
      - /etc/letsencrypt/live/skill-test.ru/privkey.pem:/etc/certs/privkey.pem
      - /etc/letsencrypt/live/skill-test.ru/cert.pem:/etc/certs/cert.pem

  mongodb:
    image: mongo
    ports:
      - "27018:27017"